version: '3'
services:

  phpfpm:
    build:
      context: ./docker
      dockerfile: phpfpm/DockerFile
    container_name: road-phpfpm
    links:
      - database
    env_file:
      - ./.env.containers
    environment:
      - PHP_IDE_CONFIG=serverName=Roadmap
    volumes:
      - ./:/var/www/html

  webserver:
    image: nginx:1.17-alpine
    container_name: road-webserver
    links:
      - phpfpm
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-storage/server-logs:/var/logs/nginx

  database:
    image: mysql:5.7
    container_name: road-database
    env_file:
      - ./.env.containers
    ports:
      - "3316:3306"
    volumes:
      - ./docker-storage/mysql-data:/var/lib/mysql
