version: '3'
services:

  phpfpm:
    build:
      context: ./docker
      dockerfile: webserver/DockerFile
    links:
      - database
    env_file:
      - ./.env
    environment:
      - PHP_IDE_CONFIG=serverName=Roadmap
    volumes:
      - ./project:/var/www/html

  webserver:
    image: nginx:1.17-alpine
    links:
      - phpfpm
    ports:
      - "80:80"
    volumes:
      - ./project:/var/www/html
      - ./docker/webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-storage/server-logs:/var/logs/nginx

  database:
    image: mysql:5.7
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - ./docker-storage/mysql-data:/var/lib/mysql
